# Generated by Django 5.2.3 on 2025-07-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
